[package]
name = "pyglzip"
version = "0.1.0"
edition = "2018"

[lib]
name = "glzip"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.1", features = ["extension-module"] }
numpy = "0.16.1"
glzip = { git = "https://github.com/jakeKonrad/glzip" }
