[package]
name = "glzip"
version = "0.1.0"
edition = "2018"

[lib]
name = "glzip"
crate-type = ["cdylib"]

[workspace]

[dependencies]
pyo3 = { version = "0.16.1", features = ["extension-module"] }
glzip_core = { path = "glzip_core", features = ["csv"] }
