name: glzip
channels:
  - pyg
  - pytorch
  - conda-forge
dependencies:
  - mypy
  - numpy
  - scipy
  - conda-forge::cudatoolkit=11.3.*
  - pytorch::pytorch=1.11.*
  - pyg::pyg
  - maturin
  - pip
  - pip:
    - ogb
